### ISSUE TITLE
Doesn't work with `ember install`

### ISSUE THREAD

**Issue by knownasilya** [pixelhandler/ember-cli-es5-shim#4]
```no-highlight
ember install ember-cli-es5-shim
version: 0.2.5
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/me/my-project/node_modules/ember-cli/lib/models/project.js:475:53
    at baseFindIndex (/Users/me/my-project/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /Users/me/my-project/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/Users/me/my-project/node_modules/ember-cli/lib/models/project.js:474:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/me/my-project/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (/Users/me/my-project/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
    at Class.<anonymous> (/Users/me/my-project/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/Users/me/my-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/me/my-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/me/my-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
```

**Comment by pixelhandler** [comment]
@knownasilya perhaps just use `npm install ember-cli-es5-shim --save-dev`
